apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envy-baseline
  namespace: argocd
spec:
  project: envy-baseline
  source:
    repoURL: https://github.com/example/application-config.git
    targetRevision: main
    path: environments/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: example-baseline
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - FailOnSharedResource=true
      - PruneLast=true

