// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: builds.sql

package sqlc

import (
	"context"
)

const claimSourceComponent = `-- name: ClaimSourceComponent :exec
INSERT INTO source_component_claims(project,component,repository) VALUES($1,$2,$3)
`

type ClaimSourceComponentParams struct {
	Project    string
	Component  string
	Repository string
}

func (q *Queries) ClaimSourceComponent(ctx context.Context, arg ClaimSourceComponentParams) error {
	_, err := q.db.Exec(ctx, claimSourceComponent, arg.Project, arg.Component, arg.Repository)
	return err
}

const enableSourceRepository = `-- name: EnableSourceRepository :one
UPDATE source_repositories SET body=jsonb_set(body,'{enabled}',to_jsonb($3::boolean)) WHERE project=$1 AND id=$2 RETURNING body
`

type EnableSourceRepositoryParams struct {
	Project string
	ID      string
	Enabled bool
}

func (q *Queries) EnableSourceRepository(ctx context.Context, arg EnableSourceRepositoryParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, enableSourceRepository, arg.Project, arg.ID, arg.Enabled)
	var body []byte
	err := row.Scan(&body)
	return body, err
}

const getBuild = `-- name: GetBuild :one
SELECT body FROM builds WHERE project=$1 AND id=$2
`

type GetBuildParams struct {
	Project string
	ID      string
}

func (q *Queries) GetBuild(ctx context.Context, arg GetBuildParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getBuild, arg.Project, arg.ID)
	var body []byte
	err := row.Scan(&body)
	return body, err
}

const getSourceRepository = `-- name: GetSourceRepository :one
SELECT body FROM source_repositories WHERE project=$1 AND id=$2
`

type GetSourceRepositoryParams struct {
	Project string
	ID      string
}

func (q *Queries) GetSourceRepository(ctx context.Context, arg GetSourceRepositoryParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSourceRepository, arg.Project, arg.ID)
	var body []byte
	err := row.Scan(&body)
	return body, err
}

const insertBuild = `-- name: InsertBuild :execrows
INSERT INTO builds(id,project,repository,component,revision,body) VALUES ($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING
`

type InsertBuildParams struct {
	ID         string
	Project    string
	Repository string
	Component  string
	Revision   string
	Body       []byte
}

func (q *Queries) InsertBuild(ctx context.Context, arg InsertBuildParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertBuild,
		arg.ID,
		arg.Project,
		arg.Repository,
		arg.Component,
		arg.Revision,
		arg.Body,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertSourceRepository = `-- name: InsertSourceRepository :execrows
INSERT INTO source_repositories(project,id,body) VALUES ($1,$2,$3) ON CONFLICT DO NOTHING
`

type InsertSourceRepositoryParams struct {
	Project string
	ID      string
	Body    []byte
}

func (q *Queries) InsertSourceRepository(ctx context.Context, arg InsertSourceRepositoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertSourceRepository, arg.Project, arg.ID, arg.Body)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBuilds = `-- name: ListBuilds :many
SELECT body FROM builds WHERE project=$1 AND repository=$2 AND component=$3 AND revision=$4 AND id > $5 ORDER BY id LIMIT $6
`

type ListBuildsParams struct {
	Project    string
	Repository string
	Component  string
	Revision   string
	After      string
	Limit      int32
}

func (q *Queries) ListBuilds(ctx context.Context, arg ListBuildsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listBuilds,
		arg.Project,
		arg.Repository,
		arg.Component,
		arg.Revision,
		arg.After,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var body []byte
		if err := rows.Scan(&body); err != nil {
			return nil, err
		}
		items = append(items, body)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceRepositories = `-- name: ListSourceRepositories :many
SELECT body FROM source_repositories WHERE project=$1 AND id > $2 ORDER BY id LIMIT $3
`

type ListSourceRepositoriesParams struct {
	Project string
	After   string
	Limit   int32
}

func (q *Queries) ListSourceRepositories(ctx context.Context, arg ListSourceRepositoriesParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listSourceRepositories, arg.Project, arg.After, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var body []byte
		if err := rows.Scan(&body); err != nil {
			return nil, err
		}
		items = append(items, body)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSourceRepository = `-- name: LockSourceRepository :one
SELECT body FROM source_repositories WHERE project=$1 AND id=$2 FOR SHARE
`

type LockSourceRepositoryParams struct {
	Project string
	ID      string
}

func (q *Queries) LockSourceRepository(ctx context.Context, arg LockSourceRepositoryParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, lockSourceRepository, arg.Project, arg.ID)
	var body []byte
	err := row.Scan(&body)
	return body, err
}
