// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package sqlc

import (
	"context"
)

const checkProjectExists = `-- name: CheckProjectExists :one
SELECT EXISTS(
    SELECT 1 FROM projects WHERE id = $1
)
`

func (q *Queries) CheckProjectExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, checkProjectExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getBaseline = `-- name: GetBaseline :one
SELECT body FROM baselines
WHERE project = $1 AND id = $2
`

type GetBaselineParams struct {
	Project string
	ID      string
}

func (q *Queries) GetBaseline(ctx context.Context, arg GetBaselineParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getBaseline, arg.Project, arg.ID)
	var body []byte
	err := row.Scan(&body)
	return body, err
}

const getComponent = `-- name: GetComponent :one
SELECT body FROM components
WHERE project = $1 AND id = $2
`

type GetComponentParams struct {
	Project string
	ID      string
}

func (q *Queries) GetComponent(ctx context.Context, arg GetComponentParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getComponent, arg.Project, arg.ID)
	var body []byte
	err := row.Scan(&body)
	return body, err
}

const insertBaseline = `-- name: InsertBaseline :exec
INSERT INTO baselines(project, id, body)
VALUES ($1, $2, $3)
`

type InsertBaselineParams struct {
	Project string
	ID      string
	Body    []byte
}

func (q *Queries) InsertBaseline(ctx context.Context, arg InsertBaselineParams) error {
	_, err := q.db.Exec(ctx, insertBaseline, arg.Project, arg.ID, arg.Body)
	return err
}

const insertBaselineHostClaim = `-- name: InsertBaselineHostClaim :exec
INSERT INTO baseline_host_claims(host, project, baseline)
VALUES ($1, $2, $3)
`

type InsertBaselineHostClaimParams struct {
	Host     string
	Project  string
	Baseline string
}

func (q *Queries) InsertBaselineHostClaim(ctx context.Context, arg InsertBaselineHostClaimParams) error {
	_, err := q.db.Exec(ctx, insertBaselineHostClaim, arg.Host, arg.Project, arg.Baseline)
	return err
}

const insertComponent = `-- name: InsertComponent :exec
INSERT INTO components(project, id, body)
VALUES ($1, $2, $3)
`

type InsertComponentParams struct {
	Project string
	ID      string
	Body    []byte
}

func (q *Queries) InsertComponent(ctx context.Context, arg InsertComponentParams) error {
	_, err := q.db.Exec(ctx, insertComponent, arg.Project, arg.ID, arg.Body)
	return err
}

const insertProject = `-- name: InsertProject :exec
INSERT INTO projects(id, body)
VALUES ($1, $2)
`

type InsertProjectParams struct {
	ID   string
	Body []byte
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) error {
	_, err := q.db.Exec(ctx, insertProject, arg.ID, arg.Body)
	return err
}

const listBaselines = `-- name: ListBaselines :many
SELECT body FROM baselines
WHERE project = $1 AND id > $2
ORDER BY id
LIMIT $3
`

type ListBaselinesParams struct {
	Project string
	ID      string
	Limit   int32
}

func (q *Queries) ListBaselines(ctx context.Context, arg ListBaselinesParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listBaselines, arg.Project, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var body []byte
		if err := rows.Scan(&body); err != nil {
			return nil, err
		}
		items = append(items, body)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComponents = `-- name: ListComponents :many
SELECT body FROM components
WHERE project = $1 AND id > $2
ORDER BY id
LIMIT $3
`

type ListComponentsParams struct {
	Project string
	ID      string
	Limit   int32
}

func (q *Queries) ListComponents(ctx context.Context, arg ListComponentsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listComponents, arg.Project, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var body []byte
		if err := rows.Scan(&body); err != nil {
			return nil, err
		}
		items = append(items, body)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT body FROM projects
WHERE id > $1
ORDER BY id
LIMIT $2
`

type ListProjectsParams struct {
	ID    string
	Limit int32
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var body []byte
		if err := rows.Scan(&body); err != nil {
			return nil, err
		}
		items = append(items, body)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedBaseline = `-- name: SeedBaseline :exec
INSERT INTO baselines(project, id, body)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type SeedBaselineParams struct {
	Project string
	ID      string
	Body    []byte
}

func (q *Queries) SeedBaseline(ctx context.Context, arg SeedBaselineParams) error {
	_, err := q.db.Exec(ctx, seedBaseline, arg.Project, arg.ID, arg.Body)
	return err
}

const seedBaselineHostClaim = `-- name: SeedBaselineHostClaim :exec
INSERT INTO baseline_host_claims(host, project, baseline)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type SeedBaselineHostClaimParams struct {
	Host     string
	Project  string
	Baseline string
}

func (q *Queries) SeedBaselineHostClaim(ctx context.Context, arg SeedBaselineHostClaimParams) error {
	_, err := q.db.Exec(ctx, seedBaselineHostClaim, arg.Host, arg.Project, arg.Baseline)
	return err
}

const seedComponent = `-- name: SeedComponent :exec
INSERT INTO components(project, id, body)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type SeedComponentParams struct {
	Project string
	ID      string
	Body    []byte
}

func (q *Queries) SeedComponent(ctx context.Context, arg SeedComponentParams) error {
	_, err := q.db.Exec(ctx, seedComponent, arg.Project, arg.ID, arg.Body)
	return err
}

const seedProject = `-- name: SeedProject :exec
INSERT INTO projects(id, body)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type SeedProjectParams struct {
	ID   string
	Body []byte
}

func (q *Queries) SeedProject(ctx context.Context, arg SeedProjectParams) error {
	_, err := q.db.Exec(ctx, seedProject, arg.ID, arg.Body)
	return err
}
