// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compositions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advisoryXactLock = `-- name: AdvisoryXactLock :exec
SELECT pg_advisory_xact_lock($1)
`

func (q *Queries) AdvisoryXactLock(ctx context.Context, pgAdvisoryXactLock int64) error {
	_, err := q.db.Exec(ctx, advisoryXactLock, pgAdvisoryXactLock)
	return err
}

const countActiveCompositions = `-- name: CountActiveCompositions :one
SELECT count(*)
FROM compositions
WHERE phase <> 'destroyed'
`

func (q *Queries) CountActiveCompositions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveCompositions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getComposition = `-- name: GetComposition :one
SELECT body, runtime, deletion_requested
FROM compositions
WHERE id = $1
`

type GetCompositionRow struct {
	Body              []byte
	Runtime           []byte
	DeletionRequested bool
}

func (q *Queries) GetComposition(ctx context.Context, id string) (GetCompositionRow, error) {
	row := q.db.QueryRow(ctx, getComposition, id)
	var i GetCompositionRow
	err := row.Scan(&i.Body, &i.Runtime, &i.DeletionRequested)
	return i, err
}

const getCompositionForUpdate = `-- name: GetCompositionForUpdate :one
SELECT body, runtime, deletion_requested
FROM compositions
WHERE id = $1
FOR UPDATE
`

type GetCompositionForUpdateRow struct {
	Body              []byte
	Runtime           []byte
	DeletionRequested bool
}

func (q *Queries) GetCompositionForUpdate(ctx context.Context, id string) (GetCompositionForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getCompositionForUpdate, id)
	var i GetCompositionForUpdateRow
	err := row.Scan(&i.Body, &i.Runtime, &i.DeletionRequested)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT request_hash, composition_id
FROM idempotency_keys
WHERE key = $1
`

type GetIdempotencyKeyRow struct {
	RequestHash   string
	CompositionID string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, key string) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, key)
	var i GetIdempotencyKeyRow
	err := row.Scan(&i.RequestHash, &i.CompositionID)
	return i, err
}

const insertComposition = `-- name: InsertComposition :exec
INSERT INTO compositions(
    id, project, baseline, generation, deletion_requested, phase, expires_at, body, runtime
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type InsertCompositionParams struct {
	ID                string
	Project           string
	Baseline          string
	Generation        int64
	DeletionRequested bool
	Phase             string
	ExpiresAt         pgtype.Timestamptz
	Body              []byte
	Runtime           []byte
}

func (q *Queries) InsertComposition(ctx context.Context, arg InsertCompositionParams) error {
	_, err := q.db.Exec(ctx, insertComposition,
		arg.ID,
		arg.Project,
		arg.Baseline,
		arg.Generation,
		arg.DeletionRequested,
		arg.Phase,
		arg.ExpiresAt,
		arg.Body,
		arg.Runtime,
	)
	return err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :exec
INSERT INTO idempotency_keys(
    key, request_hash, composition_id
) VALUES (
    $1, $2, $3
)
`

type InsertIdempotencyKeyParams struct {
	Key           string
	RequestHash   string
	CompositionID string
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, insertIdempotencyKey, arg.Key, arg.RequestHash, arg.CompositionID)
	return err
}

const listActiveCompositions = `-- name: ListActiveCompositions :many
SELECT body, runtime, deletion_requested
FROM compositions
WHERE phase <> 'destroyed'
ORDER BY id
`

type ListActiveCompositionsRow struct {
	Body              []byte
	Runtime           []byte
	DeletionRequested bool
}

func (q *Queries) ListActiveCompositions(ctx context.Context) ([]ListActiveCompositionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveCompositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveCompositionsRow
	for rows.Next() {
		var i ListActiveCompositionsRow
		if err := rows.Scan(&i.Body, &i.Runtime, &i.DeletionRequested); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompositions = `-- name: ListCompositions :many
SELECT body, runtime, deletion_requested
FROM compositions
WHERE ($1::text = '' OR project = $1::text)
  AND id > $2::text
ORDER BY id
LIMIT $3::int
`

type ListCompositionsParams struct {
	Project string
	After   string
	Limit   int32
}

type ListCompositionsRow struct {
	Body              []byte
	Runtime           []byte
	DeletionRequested bool
}

func (q *Queries) ListCompositions(ctx context.Context, arg ListCompositionsParams) ([]ListCompositionsRow, error) {
	rows, err := q.db.Query(ctx, listCompositions, arg.Project, arg.After, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompositionsRow
	for rows.Next() {
		var i ListCompositionsRow
		if err := rows.Scan(&i.Body, &i.Runtime, &i.DeletionRequested); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredCompositionsForUpdate = `-- name: ListExpiredCompositionsForUpdate :many
SELECT body, runtime, deletion_requested
FROM compositions
WHERE expires_at <= $1
  AND NOT deletion_requested
  AND phase <> 'destroyed'
FOR UPDATE SKIP LOCKED
`

type ListExpiredCompositionsForUpdateRow struct {
	Body              []byte
	Runtime           []byte
	DeletionRequested bool
}

func (q *Queries) ListExpiredCompositionsForUpdate(ctx context.Context, expiresAt pgtype.Timestamptz) ([]ListExpiredCompositionsForUpdateRow, error) {
	rows, err := q.db.Query(ctx, listExpiredCompositionsForUpdate, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredCompositionsForUpdateRow
	for rows.Next() {
		var i ListExpiredCompositionsForUpdateRow
		if err := rows.Scan(&i.Body, &i.Runtime, &i.DeletionRequested); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompositionDeletion = `-- name: UpdateCompositionDeletion :exec
UPDATE compositions
SET generation = $2, deletion_requested = true, phase = $3, body = $4, runtime = $5
WHERE id = $1
`

type UpdateCompositionDeletionParams struct {
	ID         string
	Generation int64
	Phase      string
	Body       []byte
	Runtime    []byte
}

func (q *Queries) UpdateCompositionDeletion(ctx context.Context, arg UpdateCompositionDeletionParams) error {
	_, err := q.db.Exec(ctx, updateCompositionDeletion,
		arg.ID,
		arg.Generation,
		arg.Phase,
		arg.Body,
		arg.Runtime,
	)
	return err
}

const updateCompositionDesired = `-- name: UpdateCompositionDesired :exec
UPDATE compositions
SET generation = $2, phase = $3, body = $4, runtime = $5
WHERE id = $1
`

type UpdateCompositionDesiredParams struct {
	ID         string
	Generation int64
	Phase      string
	Body       []byte
	Runtime    []byte
}

func (q *Queries) UpdateCompositionDesired(ctx context.Context, arg UpdateCompositionDesiredParams) error {
	_, err := q.db.Exec(ctx, updateCompositionDesired,
		arg.ID,
		arg.Generation,
		arg.Phase,
		arg.Body,
		arg.Runtime,
	)
	return err
}

const updateCompositionObservation = `-- name: UpdateCompositionObservation :execrows
UPDATE compositions
SET phase = $2, body = $3, runtime = $4
WHERE id = $1 AND generation = $5 AND deletion_requested = $6
`

type UpdateCompositionObservationParams struct {
	ID                string
	Phase             string
	Body              []byte
	Runtime           []byte
	Generation        int64
	DeletionRequested bool
}

func (q *Queries) UpdateCompositionObservation(ctx context.Context, arg UpdateCompositionObservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCompositionObservation,
		arg.ID,
		arg.Phase,
		arg.Body,
		arg.Runtime,
		arg.Generation,
		arg.DeletionRequested,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertOperation = `-- name: UpsertOperation :exec
INSERT INTO operations(id, composition_id, body)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET
    body = excluded.body,
    updated_at = now()
`

type UpsertOperationParams struct {
	ID            string
	CompositionID string
	Body          []byte
}

func (q *Queries) UpsertOperation(ctx context.Context, arg UpsertOperationParams) error {
	_, err := q.db.Exec(ctx, upsertOperation, arg.ID, arg.CompositionID, arg.Body)
	return err
}
