// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listLifecycleEvents = `-- name: ListLifecycleEvents :many
SELECT id, occurred_at, kind, body
FROM lifecycle_events
WHERE composition_id = $1 AND id > $2
ORDER BY id
LIMIT $3
`

type ListLifecycleEventsParams struct {
	CompositionID string
	ID            int64
	Limit         int32
}

type ListLifecycleEventsRow struct {
	ID         int64
	OccurredAt pgtype.Timestamptz
	Kind       string
	Body       []byte
}

func (q *Queries) ListLifecycleEvents(ctx context.Context, arg ListLifecycleEventsParams) ([]ListLifecycleEventsRow, error) {
	rows, err := q.db.Query(ctx, listLifecycleEvents, arg.CompositionID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLifecycleEventsRow
	for rows.Next() {
		var i ListLifecycleEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.Kind,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
