// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: frontend.sql

package sqlc

import (
	"context"
)

const countFrontendBindings = `-- name: CountFrontendBindings :one
SELECT count(*) FROM frontend_bindings WHERE composition=$1
`

func (q *Queries) CountFrontendBindings(ctx context.Context, composition string) (int64, error) {
	row := q.db.QueryRow(ctx, countFrontendBindings, composition)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFrontendBinding = `-- name: GetFrontendBinding :one
SELECT body FROM frontend_bindings WHERE project=$1 AND frontend=$2 AND revision=$3
`

type GetFrontendBindingParams struct {
	Project  string
	Frontend string
	Revision string
}

func (q *Queries) GetFrontendBinding(ctx context.Context, arg GetFrontendBindingParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getFrontendBinding, arg.Project, arg.Frontend, arg.Revision)
	var body []byte
	err := row.Scan(&body)
	return body, err
}

const getFrontendBindingForUpdate = `-- name: GetFrontendBindingForUpdate :one
SELECT body FROM frontend_bindings WHERE project=$1 AND frontend=$2 AND revision=$3 FOR UPDATE
`

type GetFrontendBindingForUpdateParams struct {
	Project  string
	Frontend string
	Revision string
}

func (q *Queries) GetFrontendBindingForUpdate(ctx context.Context, arg GetFrontendBindingForUpdateParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getFrontendBindingForUpdate, arg.Project, arg.Frontend, arg.Revision)
	var body []byte
	err := row.Scan(&body)
	return body, err
}

const insertFrontendBinding = `-- name: InsertFrontendBinding :execrows
INSERT INTO frontend_bindings(project,frontend,revision,composition,body) VALUES ($1,$2,$3,$4,$5)
ON CONFLICT (project,frontend,revision) DO NOTHING
`

type InsertFrontendBindingParams struct {
	Project     string
	Frontend    string
	Revision    string
	Composition string
	Body        []byte
}

func (q *Queries) InsertFrontendBinding(ctx context.Context, arg InsertFrontendBindingParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertFrontendBinding,
		arg.Project,
		arg.Frontend,
		arg.Revision,
		arg.Composition,
		arg.Body,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listFrontendBindings = `-- name: ListFrontendBindings :many
SELECT body FROM frontend_bindings WHERE composition=$1
AND frontend || ':' || revision > $2::text
ORDER BY frontend, revision LIMIT $3::int
`

type ListFrontendBindingsParams struct {
	Composition string
	After       string
	Limit       int32
}

func (q *Queries) ListFrontendBindings(ctx context.Context, arg ListFrontendBindingsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listFrontendBindings, arg.Composition, arg.After, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var body []byte
		if err := rows.Scan(&body); err != nil {
			return nil, err
		}
		items = append(items, body)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFrontendBinding = `-- name: UpdateFrontendBinding :exec
UPDATE frontend_bindings SET body=$4 WHERE project=$1 AND frontend=$2 AND revision=$3
`

type UpdateFrontendBindingParams struct {
	Project  string
	Frontend string
	Revision string
	Body     []byte
}

func (q *Queries) UpdateFrontendBinding(ctx context.Context, arg UpdateFrontendBindingParams) error {
	_, err := q.db.Exec(ctx, updateFrontendBinding,
		arg.Project,
		arg.Frontend,
		arg.Revision,
		arg.Body,
	)
	return err
}
