// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lease.sql

package sqlc

import (
	"context"
)

const advisoryUnlock = `-- name: AdvisoryUnlock :one
SELECT pg_advisory_unlock($1)
`

func (q *Queries) AdvisoryUnlock(ctx context.Context, pgAdvisoryUnlock int64) (bool, error) {
	row := q.db.QueryRow(ctx, advisoryUnlock, pgAdvisoryUnlock)
	var pg_advisory_unlock bool
	err := row.Scan(&pg_advisory_unlock)
	return pg_advisory_unlock, err
}

const checkAdvisoryLock = `-- name: CheckAdvisoryLock :one
SELECT EXISTS(
    SELECT 1 FROM pg_locks
    WHERE locktype = 'advisory'
      AND pid = pg_backend_pid()
      AND classid = 0
      AND objid = ($1::bigint)::oid
      AND objsubid = 1
      AND granted
)
`

func (q *Queries) CheckAdvisoryLock(ctx context.Context, dollar_1 int64) (bool, error) {
	row := q.db.QueryRow(ctx, checkAdvisoryLock, dollar_1)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const tryAdvisoryLock = `-- name: TryAdvisoryLock :one
SELECT pg_try_advisory_lock($1)
`

func (q *Queries) TryAdvisoryLock(ctx context.Context, pgTryAdvisoryLock int64) (bool, error) {
	row := q.db.QueryRow(ctx, tryAdvisoryLock, pgTryAdvisoryLock)
	var pg_try_advisory_lock bool
	err := row.Scan(&pg_try_advisory_lock)
	return pg_try_advisory_lock, err
}
