// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: migrations.sql

package sqlc

import (
	"context"
)

const checkMigrationApplied = `-- name: CheckMigrationApplied :one
SELECT EXISTS(
    SELECT 1 FROM envy_schema_migrations WHERE name = $1
)
`

func (q *Queries) CheckMigrationApplied(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, checkMigrationApplied, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const recordMigration = `-- name: RecordMigration :exec
INSERT INTO envy_schema_migrations(name) VALUES ($1)
`

func (q *Queries) RecordMigration(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, recordMigration, name)
	return err
}
