// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Baseline struct {
	Project string
	ID      string
	Body    []byte
}

type BaselineHostClaim struct {
	Host     string
	Project  string
	Baseline string
}

type Build struct {
	ID         string
	Project    string
	Repository string
	Component  string
	Revision   string
	Body       []byte
}

type Component struct {
	Project string
	ID      string
	Body    []byte
}

type Composition struct {
	ID                string
	Project           string
	Baseline          string
	Generation        int64
	DeletionRequested bool
	Phase             string
	ExpiresAt         pgtype.Timestamptz
	Body              []byte
	Runtime           []byte
}

type EnvySchemaMigration struct {
	Name      string
	AppliedAt pgtype.Timestamptz
}

type FrontendBinding struct {
	Project     string
	Frontend    string
	Revision    string
	Composition string
	Body        []byte
}

type IdempotencyKey struct {
	Key           string
	RequestHash   string
	CompositionID string
}

type LifecycleEvent struct {
	ID            int64
	CompositionID string
	OccurredAt    pgtype.Timestamptz
	Kind          string
	Body          []byte
}

type Operation struct {
	ID            string
	CompositionID string
	Body          []byte
	UpdatedAt     pgtype.Timestamptz
}

type PgLock struct {
	Locktype string
	Pid      int32
	Classid  int32
	Objid    pgtype.Uint32
	Objsubid int32
	Granted  bool
}

type Project struct {
	ID   string
	Body []byte
}

type SourceComponentClaim struct {
	Project    string
	Component  string
	Repository string
}

type SourceRepository struct {
	Project string
	ID      string
	Body    []byte
}
