// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityEvent struct {
	ID           int64
	OccurredAt   pgtype.Timestamptz
	Project      string
	ActorID      string
	Action       string
	Outcome      string
	ResourceType string
	ResourceID   string
	Body         []byte
	OperationID  string
}

type Baseline struct {
	Project string
	ID      string
	Body    []byte
}

type BaselineHostClaim struct {
	Host     string
	Project  string
	Baseline string
}

type Build struct {
	ID         string
	Project    string
	Repository string
	Component  string
	Revision   string
	Body       []byte
}

type Component struct {
	Project string
	ID      string
	Body    []byte
}

type Composition struct {
	ID                string
	Project           string
	Baseline          string
	Generation        int64
	DeletionRequested bool
	Phase             string
	ExpiresAt         pgtype.Timestamptz
	Body              []byte
	Runtime           []byte
}

type CompositionRevision struct {
	CompositionID string
	Generation    int64
	Project       string
	CreatedAt     pgtype.Timestamptz
	Body          []byte
}

type CompositionUpdateIdempotency struct {
	CompositionID string
	Key           string
	RequestHash   string
	OperationID   string
	CreatedAt     pgtype.Timestamptz
}

type EnvyAuthRecord struct {
	Kind      string
	Key       string
	Body      []byte
	ExpiresAt pgtype.Timestamptz
}

type EnvySchemaMigration struct {
	Name      string
	AppliedAt pgtype.Timestamptz
}

type FrontendBinding struct {
	Project     string
	Frontend    string
	Revision    string
	Composition string
	Body        []byte
}

type GithubPrPreview struct {
	ID            string
	Project       string
	Repository    string
	Number        int32
	Version       int64
	CompositionID pgtype.Text
	Body          []byte
}

type GithubPreviewHealth struct {
	ID           bool
	ReconciledAt pgtype.Timestamptz
	Error        string
}

type GithubPreviewHistory struct {
	PreviewID string
	Lifecycle int64
	Body      []byte
}

type GithubPreviewPolicy struct {
	Project            string
	Repository         string
	GithubRepositoryID int64
	Enabled            bool
	Body               []byte
}

type GithubWebhookDelivery struct {
	ID          string
	Event       string
	Body        []byte
	ReceivedAt  pgtype.Timestamptz
	ProcessedAt pgtype.Timestamptz
	Error       string
}

type IdempotencyKey struct {
	Key           string
	RequestHash   string
	CompositionID string
}

type InstallationProfile struct {
	Singleton                  bool
	InstallationID             string
	Provider                   string
	NamespacePolicyMode        string
	NamespacePolicyFingerprint string
}

type LifecycleEvent struct {
	ID            int64
	CompositionID string
	OccurredAt    pgtype.Timestamptz
	Kind          string
	Body          []byte
}

type Operation struct {
	ID            string
	CompositionID string
	Body          []byte
	UpdatedAt     pgtype.Timestamptz
}

type PgLock struct {
	Locktype string
	Pid      int32
	Classid  int32
	Objid    pgtype.Uint32
	Objsubid int32
	Granted  bool
}

type PreviewProfile struct {
	Project   string
	Baseline  string
	Component string
	Revision  int64
	Body      []byte
}

type Project struct {
	ID   string
	Body []byte
}

type SourceComponentClaim struct {
	Project    string
	Component  string
	Repository string
}

type SourceRepository struct {
	Project string
	ID      string
	Body    []byte
}

type VerificationEvidence struct {
	ID            int64
	CompositionID string
	Body          []byte
}
