// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification.sql

package sqlc

import (
	"context"
)

const insertVerification = `-- name: InsertVerification :exec
INSERT INTO verification_evidence(composition_id, body) VALUES ($1, $2)
`

type InsertVerificationParams struct {
	CompositionID string
	Body          []byte
}

func (q *Queries) InsertVerification(ctx context.Context, arg InsertVerificationParams) error {
	_, err := q.db.Exec(ctx, insertVerification, arg.CompositionID, arg.Body)
	return err
}

const latestVerification = `-- name: LatestVerification :many
SELECT id, body FROM verification_evidence WHERE composition_id = $1 ORDER BY id DESC LIMIT 1
`

type LatestVerificationRow struct {
	ID   int64
	Body []byte
}

func (q *Queries) LatestVerification(ctx context.Context, compositionID string) ([]LatestVerificationRow, error) {
	rows, err := q.db.Query(ctx, latestVerification, compositionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestVerificationRow
	for rows.Next() {
		var i LatestVerificationRow
		if err := rows.Scan(&i.ID, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerification = `-- name: ListVerification :many
SELECT id, body FROM verification_evidence
WHERE composition_id = $1 AND ($2::bigint = 0 OR id < $2::bigint)
ORDER BY id DESC LIMIT $3::int
`

type ListVerificationParams struct {
	CompositionID string
	Before        int64
	Limit         int32
}

type ListVerificationRow struct {
	ID   int64
	Body []byte
}

func (q *Queries) ListVerification(ctx context.Context, arg ListVerificationParams) ([]ListVerificationRow, error) {
	rows, err := q.db.Query(ctx, listVerification, arg.CompositionID, arg.Before, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVerificationRow
	for rows.Next() {
		var i ListVerificationRow
		if err := rows.Scan(&i.ID, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVerification = `-- name: UpdateVerification :exec
UPDATE verification_evidence SET body = $2 WHERE id = $1
`

type UpdateVerificationParams struct {
	ID   int64
	Body []byte
}

func (q *Queries) UpdateVerification(ctx context.Context, arg UpdateVerificationParams) error {
	_, err := q.db.Exec(ctx, updateVerification, arg.ID, arg.Body)
	return err
}
